//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEFProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetails
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string Price { get; set; }
        public string Category { get; set; }
        public string AuthorName { get; set; }
        public string Edition { get; set; }
        public string BookCondition { get; set; }
        public string Available { get; set; }
    }
}
